### PR TITLE
Add variables for user, context and namespace

### PR DESCRIPTION
**Pull request by jkrnak**
First thing: thanks for the great plugin!

### Notes:
I needed a bit more logic on my prompt based on the user, namespace and context. 
I added separate variables for these so I can add different colors or change the prompt easily in the prompt plugin. 

Let me know what you think.

### CODE REVIEW

**Review by SmithPeder — COMMENTED** [review]
+1 from me, I like this idé.

Quick note: The namespace is already calculated at line 69 and given the name `ns`. So if you move your chances under `73: ZSH_KUBECTL_PROMT` you can use the `ns` when setting the `NAMESPACE` environment variable. Then it also gets the "default" name if it's not set.

**Comment by superbrothers** [comment]
@jkrnak Thank you for your contribution! This is an useful change.

> So if you move your chances under 73: ZSH_KUBECTL_PROMT you can use the ns when setting the NAMESPACE environment variable. Then it also gets the "default" name if it's not set.

Yes, it seems a little redundant. Please change as @SmithPeder said.

**Comment by jkrnak** [comment]
Great call @SmithPeder ! I'll change it, thanks

But I will need to move line 69 instead above, as on line 64-67 we might return prematurely if the user decides not to display the namespace in prompt.

**Comment by jkrnak** [comment]
I made the changes. Let me know what you think.

Should we be concerned about fetching the extra vars even if they are not needed? 
Maybe we could add toggles for them like the `namespace` into the prompt.

**Comment by superbrothers** [comment]
No problem. The extra vars don't be fetched again if kubeconfig file is not changed. This change will make it a bit heavier, but it will be a small impact.

**Review by superbrothers — APPROVED** [review]

**Pull request merged**
